#!/bin/bash
# Установка:
# sudo cp googleit /usr/bin
# или
# sudo cp googleit /bin

q=""
i=0

for var in "$@"
do
   if [ "$i" -eq "0" ]
   then
      q+=$var
   else
      q+="+"$var
   fi
   i+=1
done

xdg-open "https://www.google.ru/search?q=$q" 
